# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

# Language and tone for reviews
language: ko
tone_instructions: "전문적이고 건설적인 피드백을 제공해주세요. 가설 검증(H1, H2, H3)과 관련된 로직의 정확성을 중점적으로 검토해주세요."

# Review settings
reviews:
  # Enable automatic reviews
  auto_review:
    enabled: true
    # Base branches to auto-review PRs targeting these branches
    base_branches:
      - main
      - master
      - develop  # develop 브랜치로 가는 PR도 자동 리뷰

  # Show review status message
  review_status: true

  # Auto-collapse bot comments after resolved
  collapse_walkthrough: false

  # Review profile
  profile: "chill"  # Options: chill, assertive

  # Request changes workflow
  request_changes_workflow: false

  # High level summary
  high_level_summary: true

  # Path filters - exclude generated/build files
  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/target/**"
    - "!**/.gradle/**"
    - "!**/bin/**"
    - "!**/*.min.js"
    - "!**/*.bundle.js"
    - "!**/package-lock.json"
    - "!**/bun.lockb"
    - "!**/yarn.lock"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.png"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.ico"

# Chat settings
chat:
  auto_reply: true

# Project context for better reviews
knowledge_base:
  learnings:
    scope: "global"
